import { TodosProvider } from '@/store/todos';
import { Open_Sans } from 'next/font/google'
import './globals.css';
 
const openSans = Open_Sans({
  weight: ['300', '500', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Todo App - NextJs + Typescript',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <TodosProvider>
          {children}
        </TodosProvider>
      </body>
    </html>
  )
}
